import type {Metadata} from "next";
import "./globals.css";
import CombinedHeader from "@/components/header/CombinedHeader";
import {Poppins} from "next/font/google";

const poppins = Poppins({
    subsets: ['latin'],
    weight: ['100', '400', '700'], // Указываем нужные веса
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{
    children: React.ReactNode;
}>) {
    console.log('Rendering RootLayout');
    return (
        <html lang="en">
            <body className={`${poppins.className} antialiased`}>
               <CombinedHeader >
                   {children}
               </CombinedHeader>
            </body>
        </html>
    );
}
