import DashboardHeader from './DashboardHeader';
import React from "react";
import { Poppins } from 'next/font/google'; // Импортируем шрифт Poppins

const poppins = Poppins({
    subsets: ['latin'],
    weight: ['100', '400', '700'], // Указываем нужные веса
});

export const metadata = {
    title: "Dashboard",
    description: "Generated by create next app",
};

const DashboardLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    return (
        <body className={`${poppins.className} antialiased`}>
        <div className='w-full'>
            <DashboardHeader />
            <main>{children}</main>
        </div>
        </body>
    );
};

export default DashboardLayout;
